version: '3.7'

volumes:
    solidity_compilers: {}
    vyper_compilers: {}
    brownie: {}
    cache: {}

networks:
  yearn-exporter:

services:
  brownie-bridge-eth:
    build: .
    image: yearn-exporter
    command: brownie_bridge
    environment:
      - NETWORK=mainnet
      - WEB3_PROVIDER
      - ETHERSCAN_TOKEN
      - EXPLORER
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPASSWORD=yearn-exporter
      - PGDATABASE=postgres
      - BRIDGE_PORT=1337
      - BRIDGE_HOST=brownie-bridge-eth
    volumes:
      - solidity_compilers:/root/.solcx
      - vyper_compilers:/root/.vvm
      - brownie:/root/.brownie
      - cache:/app/yearn-exporter/cache
    networks:
      - yearn-exporter
    restart: on-failure

  brownie-bridge-ftm:
    build: .
    image: yearn-exporter
    command: brownie_bridge
    environment:
      - NETWORK=ftm-main
      - WEB3_PROVIDER=$FTM_WEB3_PROVIDER
      - EXPLORER=$FTM_EXPLORER
      - FTMSCAN_TOKEN
      - SLEEP_SECONDS
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPASSWORD=yearn-exporter
      - PGDATABASE=postgres
      - BRIDGE_PORT=1337
      - BRIDGE_HOST=brownie-bridge-ftm
    volumes:
      - solidity_compilers:/root/.solcx
      - vyper_compilers:/root/.vvm
      - brownie:/root/.brownie
      - cache:/app/yearn-exporter/cache
    networks:
      - yearn-exporter
    restart: on-failure

  brownie-api:
    image: yearn-exporter
    entrypoint: uvicorn brownie_bridge.api:app --host 0.0.0.0 --port 4004
    environment:
      - WEB3_PROVIDER
      - ETHERSCAN_TOKEN
      - EXPLORER
      - SLEEP_SECONDS
      - POOL_SIZE
      - CHUNK_SIZE
      - RESOLUTION
      - SKIP_WALLET_STATS
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPASSWORD=yearn-exporter
      - PGDATABASE=postgres
      - BRIDGE_HOST=brownie_bridge
      - BRIDGE_PORT=1337
    ports:
      - 127.0.0.1:4004:4004
    volumes:
      - solidity_compilers:/root/.solcx
      - vyper_compilers:/root/.vvm
      - brownie:/root/.brownie
      - cache:/app/yearn-exporter/cache
    networks:
      - yearn-exporter
    restart: on-failure
